### ISSUE TITLE
Add a link to Taskwarrior ?

### ISSUE THREAD

**Issue by etiennelb** [jyguyomarch/awesome-productivity#21]
Taskwarrior is Free and Open Source Software that manages your TODO list from your command line. It is flexible, fast, efficient, and unobtrusive.

I use it for a few years and it's great if you like CLI.

http://taskwarrior.org/

Thanks.

**Comment by jyguyomarch** [comment]
Thx for the tip @etiennelb 

Definitely goes on the list.

**Comment by jyguyomarch** [comment]
Added.
